export const routes = {
  HOMEPAGE: '/',
  ADMIN: '/admin',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  SIGNOUT: '/signout',
  REGISTER: '/register',
  PRIVATE: '/admin/private',
  FORBIDDEN: '/forbidden',
  BLOG: '/blog',
  NOTFOUND: '/404',
  CREATE_POST: '/admin/create-post',
  PREVIEW_POST: '/admin/post/preview',
  USERS: '/admin/users',
  PRODUCT: '/product',
};
